// Package demo GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package demo

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/info": {
            "get": {
                "description": "用户信息",
                "tags": [
                    "user"
                ],
                "responses": {
                    "200": {
                        "description": "code==0请求成功，否则请求失败！",
                        "schema": {
                            "$ref": "#/definitions/jwt.User"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "用户登录",
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code==0请求成功，否则请求失败！",
                        "schema": {
                            "$ref": "#/definitions/service.LoginRes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "jwt.User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "roleID": {
                    "type": "integer"
                }
            }
        },
        "service.LoginReq": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "service.LoginRes": {
            "type": "object",
            "properties": {
                "expire": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:20105",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "DEMO API",
	Description:      "This is api document",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
